import { Role } from 'src/config/guardianTags'
import StatusCode from '../status'

const language = {
	middleware: {
		ensureRole: {
			policyRequired:
				'A role can only be enforced when connected to a policy',
			policyDoesNotExist: 'A policy cannot be found with that id',
			[Role.STANDARD_REGISTRY]:
				'Only a "STANDARD_REGISTRY" policy owner may approve a project, site or query related block data',
			[Role.VERIFIER]:
				'Only a user with the role "VERIFIER" make approve an claim (MRV) block or query related block data',
			[Role.SUPPLIER]:
				'Only a user with the role "SUPPLIER" may submit this document or query related block data',
		},
		withAuthenticationResponse: {
			noAccessToken:
				'Please set a valid Bearer JWT in your "Authorization" header. A new JWT can be generated by logging in.',
			invalidAuthType: (type: string) =>
				`The Authorization type should be Bearer, not ${type}.`,
		},
		onlyPostResponse: {
			notAllowed: (method: string) =>
				`Method ${method} is not allowed on this route`,
		},
		queryResponse: {
			invalidType: (validValues: string) =>
				`The policy can only query types of ${validValues}. Please update your request.`,
		},
		ensureMrv: {
			unknownMrv: 'No MRV found with that id',
		},
		validate: {
			message: 'Validation errors',
			invalidRole: "Invalid role type. Must be 'supplier' or 'verifier'",
		},
		guardian: {
			serverError:
				'💥 Guardian API server error… your guess is as good as ours… 🤷‍♂️',
		},
		hmac: {
			noHost: 'Missing "host" in header',
			noSignature: 'Missing HMAC "x-signature" in header',
			noDate: 'Missing "x-date" in header',
			invalidDate:
				'"x-date" header should be an ISO 8601 UTC date string',
			noContentHash:
				'Missing "x-content-sha256" in header. This should be a base64 encoded sha256 hash of the request body',
			requestTooOld:
				'Request "x-date" is too old. Please re-create the request.',
			invalidContentHash:
				'Request body hash does not match the hash provided in the header for "x-content-sha256"',
			invalidSignature:
				'HMAC signature is invalid. Please make sure you are using the correct key and following the correct format.',
		},
	},

	// Standard API error status code messages
	errorCode: {
		[StatusCode.BAD_REQUEST]: 'Bad Request',
		[StatusCode.UNAUTHORIZED]: 'Unauthorized',
		[StatusCode.NOT_FOUND]: 'Not Found',
		[StatusCode.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
		[StatusCode.UNPROCESSIBLE_ENTITY]: 'Unprocessable Entity',
		[StatusCode.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
	},

	// Requests
	statusRequest: {
		message: 'Your environment status for your client',
		meta_hint:
			'Hide this status endpoint by setting "HIDE_STATUS=TRUE" in your environment',
	},
}

export default language
