# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        - cron: '0 9 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            HEDERA_NETWORK: ${{ secrets.HEDERA_NETWORK }}
            HEDERA_OPERATOR_ACCOUNT_ID: ${{ secrets.HEDERA_OPERATOR_ACCOUNT_ID }}
            HEDERA_OPERATOR_PRIVATE_KEY: ${{ secrets.HEDERA_OPERATOR_PRIVATE_KEY }}
            GUARDIAN_API_URL: ${{ secrets.GUARDIAN_API_URL }}
            HMAC_SECRET_KEY: ${{ secrets.HMAC_SECRET_KEY }}
            ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
            API_URL: ${{ secrets.API_URL }}
            HIDE_STATUS: ${{ secrets.HIDE_STATUS }}
            TEST_AUTH_URL: ${{ secrets.TEST_AUTH_URL }}

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - run: yarn install --frozen-lockfile
            - run: yarn run build
            - run: yarn lint
            - run: yarn format
            - run: yarn types
            - run: yarn test
